run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - errorlint
    - forbidigo
    - gocritic
    - revive
    - unconvert
    - unparam
    - misspell
    - bodyclose
    - gofmt
    - goimports
    - govet
    - unused
    - ineffassign

linters-settings:
  forbidigo:
    forbid:
      - pattern: '^fmt\.(Printf|Println)$'
        msg: "use zerolog instead of fmt for output"
      - pattern: '^log\.(Print|Println|Printf)$'
        msg: "use zerolog instead of stdlib log"
