pre-commit:
  parallel: true
  commands:
    gofmt:
      glob: "**/*.go"
      run: gofmt -l {staged_files} | xargs -r false
    goimports:
      glob: "**/*.go"
      run: goimports -l {staged_files} | xargs -r false
    govet:
      run: cd server && go vet ./...
