package redisx

import (
	"context"
	"encoding/json"
	"time"

	"github.com/redis/go-redis/v9"

	"github.com/huing/cat/server/pkg/clockx"
)

// ResumeSnapshot is the value cached per user for `session.resume`. Defined in
// pkg/redisx (and not internal/ws) because Go uses nominal typing for
// interface method signatures: the RedisResumeCache methods must reference the
// same concrete type ws.ResumeCache declares. internal/ws re-exports it via a
// type alias so business code treats it as a ws-layer value while the physical
// location respects the pkg → internal dependency direction. This is the same
// pattern DedupResult and ConnectDecision follow.
//
// Each content field is opaque JSON (json.RawMessage) so Epic 1 / 2 / 3 / 6 /
// 7 can evolve their domain shapes without coupling this file. ServerTime is
// *not* persisted — it is regenerated by the handler on every response so
// cache hits still carry the current server clock.
type ResumeSnapshot struct {
	User         json.RawMessage `json:"user"`
	Friends      json.RawMessage `json:"friends"`
	CatState     json.RawMessage `json:"catState"`
	Skins        json.RawMessage `json:"skins"`
	Blindboxes   json.RawMessage `json:"blindboxes"`
	RoomSnapshot json.RawMessage `json:"roomSnapshot"`
	ServerTime   string          `json:"serverTime"`
}

// RedisResumeCache implements the WS session.resume cache (`resume_cache:{userID}`
// Redis Hash) as well as the Service-layer invalidation contract. One concrete
// type satisfies both ws.ResumeCache (read/write from the handler) and
// ws.ResumeCacheInvalidator (DEL from post-commit service hooks) through Go's
// structural typing — same pattern RedisDedupStore uses for ws.DedupStore and
// RedisBlacklist uses for ws.Blacklist.
//
// # Key space (D16 — PRD §Redis Key Convention lines 547-554)
//
//	resume_cache:{userID}  →  Hash { user, friends, catState, skins, blindboxes, roomSnapshot }
//
// Separated from event:* / event_result:* / lock:cron:* / ratelimit:ws:* /
// blacklist:device:* / presence:* / state:* / refresh_blacklist:*. Single-
// segment concatenation is safe because userID comes from the JWT subject and
// has a controlled format (ObjectID hex / UUID / debug bearer token, none of
// which contain ":") — contrast with RedisDedupStore which joins multiple
// free-form fields and therefore uses length-prefix encoding.
//
// # ServerTime is *not* persisted
//
// ResumeSnapshot carries a ServerTime field for client clock-skew estimation,
// but Put writes only the six content fields; the handler re-stamps ServerTime
// from the injected Clock on every response. Caching ServerTime would make a
// cache hit report a stale clock and falsely signal large skew to the client.
type RedisResumeCache struct {
	cmd   redis.Cmdable
	clock clockx.Clock
	ttl   time.Duration
}

// NewResumeCache panics on nil clock or non-positive ttl. Fail fast at
// startup: a silently-disabled cache would mean every session.resume hits
// Mongo (the exact behaviour FR42 exists to prevent), so the cost of a clear
// boot-time crash is preferable to a silent regression into J4.
func NewResumeCache(cmd redis.Cmdable, clock clockx.Clock, ttl time.Duration) *RedisResumeCache {
	if clock == nil {
		panic("redisx.NewResumeCache: clock must not be nil")
	}
	if ttl <= 0 {
		panic("redisx.NewResumeCache: ttl must be > 0")
	}
	return &RedisResumeCache{cmd: cmd, clock: clock, ttl: ttl}
}

func resumeCacheKey(userID string) string {
	return "resume_cache:" + userID
}

// Hash field names. Stable constants rather than inline literals so that a
// typo in Get / Put doesn't silently produce a cache miss with no test
// signal — the constants are compared against live Redis keys in
// TestResumeCache_PutGetRoundTrip.
const (
	fieldUser         = "user"
	fieldFriends      = "friends"
	fieldCatState     = "catState"
	fieldSkins        = "skins"
	fieldBlindboxes   = "blindboxes"
	fieldRoomSnapshot = "roomSnapshot"
)

// Get loads a cached snapshot. found=false on a clean cache miss (no hash or
// TTL expired). ServerTime on the returned snapshot is the zero string — the
// caller must stamp it from their own Clock before marshaling the response.
func (c *RedisResumeCache) Get(ctx context.Context, userID string) (ResumeSnapshot, bool, error) {
	m, err := c.cmd.HGetAll(ctx, resumeCacheKey(userID)).Result()
	if err != nil {
		return ResumeSnapshot{}, false, err
	}
	if len(m) == 0 {
		return ResumeSnapshot{}, false, nil
	}
	snap := ResumeSnapshot{
		User:         rawFromString(m[fieldUser]),
		Friends:      rawFromString(m[fieldFriends]),
		CatState:     rawFromString(m[fieldCatState]),
		Skins:        rawFromString(m[fieldSkins]),
		Blindboxes:   rawFromString(m[fieldBlindboxes]),
		RoomSnapshot: rawFromString(m[fieldRoomSnapshot]),
	}
	return snap, true, nil
}

// Put writes the six content fields and resets the TTL. Pipelined — atomicity
// across the Hash fields and the EXPIRE is not strictly required (all writes
// are idempotent), but a single RTT is cheap and avoids a partial-write window
// where HSET succeeded but EXPIRE didn't (which would leave the key alive
// forever in the no-eviction case).
func (c *RedisResumeCache) Put(ctx context.Context, userID string, snapshot ResumeSnapshot) error {
	key := resumeCacheKey(userID)
	pipe := c.cmd.Pipeline()
	pipe.HSet(ctx, key,
		fieldUser, rawToString(snapshot.User),
		fieldFriends, rawToString(snapshot.Friends),
		fieldCatState, rawToString(snapshot.CatState),
		fieldSkins, rawToString(snapshot.Skins),
		fieldBlindboxes, rawToString(snapshot.Blindboxes),
		fieldRoomSnapshot, rawToString(snapshot.RoomSnapshot),
	)
	pipe.Expire(ctx, key, c.ttl)
	_, err := pipe.Exec(ctx)
	return err
}

// Invalidate DELs the Hash. DEL on a missing key is a Redis no-op (returns 0
// without error), so services that double-invalidate or invalidate after
// natural TTL expiry do not need to special-case.
func (c *RedisResumeCache) Invalidate(ctx context.Context, userID string) error {
	return c.cmd.Del(ctx, resumeCacheKey(userID)).Err()
}

// rawToString normalizes a json.RawMessage for Redis storage. A nil / empty
// RawMessage is stored as the JSON literal "null" so downstream Get always
// yields valid JSON — an empty string would later marshal into the response
// as an invalid token, and go-redis treats "" as present-but-empty which
// would not trigger a cache-miss branch in Get.
func rawToString(r json.RawMessage) string {
	if len(r) == 0 {
		return "null"
	}
	return string(r)
}

// rawFromString rehydrates a json.RawMessage from a Redis hash field. Missing
// keys arrive as "" from HGETALL; we preserve that as JSON "null" so the
// downstream response always contains valid JSON for every field.
func rawFromString(s string) json.RawMessage {
	if s == "" {
		return json.RawMessage(`null`)
	}
	return json.RawMessage(s)
}
